name: fantasygolf
recipe: laravel
config:
  composer_version: '2-latest'
  webroot: ./public
  database: mysql:8.0
  via: nginx
  cache: redis
tooling:
  art:
    service: appserver
    description: Run an Artisan command
    cmd: php artisan
